require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/ExampleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15